services:
    app:
        build: .
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        network_mode: "host"

    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: innoscripta
        network_mode: "host"


